apiVersion: v1
kind: Secret
metadata:
  name: model-auth-secret
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: kserve-demo
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sentiment-classifier-auth"
  annotations:
    serving.kserve.io/enable-auth: "true"
    serving.kserve.io/auth-secret: "model-auth-secret"
spec:
  predictor:
    containers:
      - name: sentiment-model
        image: akshaymittal143/sentiment-model:v1
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"