apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sentiment-classifier"
spec:
  predictor:
    containers:
      - name: sentiment-model
        image: akshaymittal143/sentiment-model:v1
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"